// Code generated by wsdl2go. DO NOT EDIT.

package countryinfoservicesoapbinding12

import (
	"github.com/fiorix/wsdl2go/soap"
)

// Namespace was auto-generated from WSDL.
var Namespace = "http://www.oorsprong.org/websamples.countryinfo"

// NewCountryInfoServiceSoapType creates an initializes a CountryInfoServiceSoapType.
func NewCountryInfoServiceSoapType(cli *soap.Client) CountryInfoServiceSoapType {
	return &countryInfoServiceSoapType{cli}
}

// CountryInfoServiceSoapType was auto-generated from WSDL
// and defines interface for the remote service. Useful for testing.
type CountryInfoServiceSoapType interface {
	// Returns the  name of the captial city for the passed country
	// code
	CapitalCity(CapitalCity *CapitalCity) (*CapitalCityResponse, error)

	// Returns a list of all countries that use the same currency code.
	// Pass a ISO currency code
	CountriesUsingCurrency(CountriesUsingCurrency *CountriesUsingCurrency) (*CountriesUsingCurrencyResponse, error)

	// Returns the currency ISO code and name for the passed country
	// ISO code
	CountryCurrency(CountryCurrency *CountryCurrency) (*CountryCurrencyResponse, error)

	// Returns a link to a picture of the country flag
	CountryFlag(CountryFlag *CountryFlag) (*CountryFlagResponse, error)

	// This function tries to found a country based on the passed country
	// name.
	CountryISOCode(CountryISOCode *CountryISOCode) (*CountryISOCodeResponse, error)

	// Returns the internation phone code for the passed ISO country
	// code
	CountryIntPhoneCode(CountryIntPhoneCode *CountryIntPhoneCode) (*CountryIntPhoneCodeResponse, error)

	// Searches the database for a country by the passed ISO country
	// code
	CountryName(CountryName *CountryName) (*CountryNameResponse, error)

	// Returns the name of the currency (if found)
	CurrencyName(CurrencyName *CurrencyName) (*CurrencyNameResponse, error)

	// Returns a struct with all the stored country information. Pass
	// the ISO country code
	FullCountryInfo(FullCountryInfo *FullCountryInfo) (*FullCountryInfoResponse, error)

	// Returns an array with all countries and all the language information
	// stored
	FullCountryInfoAllCountries(FullCountryInfoAllCountries *FullCountryInfoAllCountries) (*FullCountryInfoAllCountriesResponse, error)

	// Find a language ISO code based on the passed language name
	LanguageISOCode(LanguageISOCode *LanguageISOCode) (*LanguageISOCodeResponse, error)

	// Find a language name based on the passed ISO language code
	LanguageName(LanguageName *LanguageName) (*LanguageNameResponse, error)

	// Returns a list of continents ordered by code.
	ListOfContinentsByCode(ListOfContinentsByCode *ListOfContinentsByCode) (*ListOfContinentsByCodeResponse, error)

	// Returns a list of continents ordered by name.
	ListOfContinentsByName(ListOfContinentsByName *ListOfContinentsByName) (*ListOfContinentsByNameResponse, error)

	// Returns a list of all stored counties ordered by ISO code
	ListOfCountryNamesByCode(ListOfCountryNamesByCode *ListOfCountryNamesByCode) (*ListOfCountryNamesByCodeResponse, error)

	// Returns a list of all stored counties ordered by country name
	ListOfCountryNamesByName(ListOfCountryNamesByName *ListOfCountryNamesByName) (*ListOfCountryNamesByNameResponse, error)

	// Returns a list of all stored counties grouped per continent
	ListOfCountryNamesGroupedByContinent(ListOfCountryNamesGroupedByContinent *ListOfCountryNamesGroupedByContinent) (*ListOfCountryNamesGroupedByContinentResponse, error)

	// Returns a list of currencies ordered by code.
	ListOfCurrenciesByCode(ListOfCurrenciesByCode *ListOfCurrenciesByCode) (*ListOfCurrenciesByCodeResponse, error)

	// Returns a list of currencies ordered by name.
	ListOfCurrenciesByName(ListOfCurrenciesByName *ListOfCurrenciesByName) (*ListOfCurrenciesByNameResponse, error)

	// Returns an array of languages ordered by code
	ListOfLanguagesByCode(ListOfLanguagesByCode *ListOfLanguagesByCode) (*ListOfLanguagesByCodeResponse, error)

	// Returns an array of languages ordered by name
	ListOfLanguagesByName(ListOfLanguagesByName *ListOfLanguagesByName) (*ListOfLanguagesByNameResponse, error)
}

// ArrayOftContinent was auto-generated from WSDL.
type ArrayOftContinent struct {
	TContinent []*TContinent `xml:"tContinent,omitempty" json:"tContinent,omitempty" yaml:"tContinent,omitempty"`
}

// ArrayOftCountryCodeAndName was auto-generated from WSDL.
type ArrayOftCountryCodeAndName struct {
	TCountryCodeAndName []*TCountryCodeAndName `xml:"tCountryCodeAndName,omitempty" json:"tCountryCodeAndName,omitempty" yaml:"tCountryCodeAndName,omitempty"`
}

// ArrayOftCountryCodeAndNameGroupedByContinent was auto-generated
// from WSDL.
type ArrayOftCountryCodeAndNameGroupedByContinent struct {
	TCountryCodeAndNameGroupedByContinent []*TCountryCodeAndNameGroupedByContinent `xml:"tCountryCodeAndNameGroupedByContinent,omitempty" json:"tCountryCodeAndNameGroupedByContinent,omitempty" yaml:"tCountryCodeAndNameGroupedByContinent,omitempty"`
}

// ArrayOftCountryInfo was auto-generated from WSDL.
type ArrayOftCountryInfo struct {
	TCountryInfo []*TCountryInfo `xml:"tCountryInfo,omitempty" json:"tCountryInfo,omitempty" yaml:"tCountryInfo,omitempty"`
}

// ArrayOftCurrency was auto-generated from WSDL.
type ArrayOftCurrency struct {
	TCurrency []*TCurrency `xml:"tCurrency,omitempty" json:"tCurrency,omitempty" yaml:"tCurrency,omitempty"`
}

// ArrayOftLanguage was auto-generated from WSDL.
type ArrayOftLanguage struct {
	TLanguage []*TLanguage `xml:"tLanguage,omitempty" json:"tLanguage,omitempty" yaml:"tLanguage,omitempty"`
}

// CapitalCity was auto-generated from WSDL.
type CapitalCity struct {
	SCountryISOCode *string `xml:"sCountryISOCode,omitempty" json:"sCountryISOCode,omitempty" yaml:"sCountryISOCode,omitempty"`
}

// CapitalCityResponse was auto-generated from WSDL.
type CapitalCityResponse struct {
	CapitalCityResult *string `xml:"CapitalCityResult,omitempty" json:"CapitalCityResult,omitempty" yaml:"CapitalCityResult,omitempty"`
}

// CountriesUsingCurrency was auto-generated from WSDL.
type CountriesUsingCurrency struct {
	SISOCurrencyCode *string `xml:"sISOCurrencyCode,omitempty" json:"sISOCurrencyCode,omitempty" yaml:"sISOCurrencyCode,omitempty"`
}

// CountriesUsingCurrencyResponse was auto-generated from WSDL.
type CountriesUsingCurrencyResponse struct {
	CountriesUsingCurrencyResult *ArrayOftCountryCodeAndName `xml:"CountriesUsingCurrencyResult,omitempty" json:"CountriesUsingCurrencyResult,omitempty" yaml:"CountriesUsingCurrencyResult,omitempty"`
}

// CountryCurrency was auto-generated from WSDL.
type CountryCurrency struct {
	SCountryISOCode *string `xml:"sCountryISOCode,omitempty" json:"sCountryISOCode,omitempty" yaml:"sCountryISOCode,omitempty"`
}

// CountryCurrencyResponse was auto-generated from WSDL.
type CountryCurrencyResponse struct {
	CountryCurrencyResult *TCurrency `xml:"CountryCurrencyResult,omitempty" json:"CountryCurrencyResult,omitempty" yaml:"CountryCurrencyResult,omitempty"`
}

// CountryFlag was auto-generated from WSDL.
type CountryFlag struct {
	SCountryISOCode *string `xml:"sCountryISOCode,omitempty" json:"sCountryISOCode,omitempty" yaml:"sCountryISOCode,omitempty"`
}

// CountryFlagResponse was auto-generated from WSDL.
type CountryFlagResponse struct {
	CountryFlagResult *string `xml:"CountryFlagResult,omitempty" json:"CountryFlagResult,omitempty" yaml:"CountryFlagResult,omitempty"`
}

// CountryISOCode was auto-generated from WSDL.
type CountryISOCode struct {
	SCountryName *string `xml:"sCountryName,omitempty" json:"sCountryName,omitempty" yaml:"sCountryName,omitempty"`
}

// CountryISOCodeResponse was auto-generated from WSDL.
type CountryISOCodeResponse struct {
	CountryISOCodeResult *string `xml:"CountryISOCodeResult,omitempty" json:"CountryISOCodeResult,omitempty" yaml:"CountryISOCodeResult,omitempty"`
}

// CountryIntPhoneCode was auto-generated from WSDL.
type CountryIntPhoneCode struct {
	SCountryISOCode *string `xml:"sCountryISOCode,omitempty" json:"sCountryISOCode,omitempty" yaml:"sCountryISOCode,omitempty"`
}

// CountryIntPhoneCodeResponse was auto-generated from WSDL.
type CountryIntPhoneCodeResponse struct {
	CountryIntPhoneCodeResult *string `xml:"CountryIntPhoneCodeResult,omitempty" json:"CountryIntPhoneCodeResult,omitempty" yaml:"CountryIntPhoneCodeResult,omitempty"`
}

// CountryName was auto-generated from WSDL.
type CountryName struct {
	SCountryISOCode *string `xml:"sCountryISOCode,omitempty" json:"sCountryISOCode,omitempty" yaml:"sCountryISOCode,omitempty"`
}

// CountryNameResponse was auto-generated from WSDL.
type CountryNameResponse struct {
	CountryNameResult *string `xml:"CountryNameResult,omitempty" json:"CountryNameResult,omitempty" yaml:"CountryNameResult,omitempty"`
}

// CurrencyName was auto-generated from WSDL.
type CurrencyName struct {
	SCurrencyISOCode *string `xml:"sCurrencyISOCode,omitempty" json:"sCurrencyISOCode,omitempty" yaml:"sCurrencyISOCode,omitempty"`
}

// CurrencyNameResponse was auto-generated from WSDL.
type CurrencyNameResponse struct {
	CurrencyNameResult *string `xml:"CurrencyNameResult,omitempty" json:"CurrencyNameResult,omitempty" yaml:"CurrencyNameResult,omitempty"`
}

// FullCountryInfo was auto-generated from WSDL.
type FullCountryInfo struct {
	SCountryISOCode *string `xml:"sCountryISOCode,omitempty" json:"sCountryISOCode,omitempty" yaml:"sCountryISOCode,omitempty"`
}

// FullCountryInfoAllCountries was auto-generated from WSDL.
type FullCountryInfoAllCountries struct {
}

// FullCountryInfoAllCountriesResponse was auto-generated from
// WSDL.
type FullCountryInfoAllCountriesResponse struct {
	FullCountryInfoAllCountriesResult *ArrayOftCountryInfo `xml:"FullCountryInfoAllCountriesResult,omitempty" json:"FullCountryInfoAllCountriesResult,omitempty" yaml:"FullCountryInfoAllCountriesResult,omitempty"`
}

// FullCountryInfoResponse was auto-generated from WSDL.
type FullCountryInfoResponse struct {
	FullCountryInfoResult *TCountryInfo `xml:"FullCountryInfoResult,omitempty" json:"FullCountryInfoResult,omitempty" yaml:"FullCountryInfoResult,omitempty"`
}

// LanguageISOCode was auto-generated from WSDL.
type LanguageISOCode struct {
	SLanguageName *string `xml:"sLanguageName,omitempty" json:"sLanguageName,omitempty" yaml:"sLanguageName,omitempty"`
}

// LanguageISOCodeResponse was auto-generated from WSDL.
type LanguageISOCodeResponse struct {
	LanguageISOCodeResult *string `xml:"LanguageISOCodeResult,omitempty" json:"LanguageISOCodeResult,omitempty" yaml:"LanguageISOCodeResult,omitempty"`
}

// LanguageName was auto-generated from WSDL.
type LanguageName struct {
	SISOCode *string `xml:"sISOCode,omitempty" json:"sISOCode,omitempty" yaml:"sISOCode,omitempty"`
}

// LanguageNameResponse was auto-generated from WSDL.
type LanguageNameResponse struct {
	LanguageNameResult *string `xml:"LanguageNameResult,omitempty" json:"LanguageNameResult,omitempty" yaml:"LanguageNameResult,omitempty"`
}

// ListOfContinentsByCode was auto-generated from WSDL.
type ListOfContinentsByCode struct {
}

// ListOfContinentsByCodeResponse was auto-generated from WSDL.
type ListOfContinentsByCodeResponse struct {
	ListOfContinentsByCodeResult *ArrayOftContinent `xml:"ListOfContinentsByCodeResult,omitempty" json:"ListOfContinentsByCodeResult,omitempty" yaml:"ListOfContinentsByCodeResult,omitempty"`
}

// ListOfContinentsByName was auto-generated from WSDL.
type ListOfContinentsByName struct {
}

// ListOfContinentsByNameResponse was auto-generated from WSDL.
type ListOfContinentsByNameResponse struct {
	ListOfContinentsByNameResult *ArrayOftContinent `xml:"ListOfContinentsByNameResult,omitempty" json:"ListOfContinentsByNameResult,omitempty" yaml:"ListOfContinentsByNameResult,omitempty"`
}

// ListOfCountryNamesByCode was auto-generated from WSDL.
type ListOfCountryNamesByCode struct {
}

// ListOfCountryNamesByCodeResponse was auto-generated from WSDL.
type ListOfCountryNamesByCodeResponse struct {
	ListOfCountryNamesByCodeResult *ArrayOftCountryCodeAndName `xml:"ListOfCountryNamesByCodeResult,omitempty" json:"ListOfCountryNamesByCodeResult,omitempty" yaml:"ListOfCountryNamesByCodeResult,omitempty"`
}

// ListOfCountryNamesByName was auto-generated from WSDL.
type ListOfCountryNamesByName struct {
}

// ListOfCountryNamesByNameResponse was auto-generated from WSDL.
type ListOfCountryNamesByNameResponse struct {
	ListOfCountryNamesByNameResult *ArrayOftCountryCodeAndName `xml:"ListOfCountryNamesByNameResult,omitempty" json:"ListOfCountryNamesByNameResult,omitempty" yaml:"ListOfCountryNamesByNameResult,omitempty"`
}

// ListOfCountryNamesGroupedByContinent was auto-generated from
// WSDL.
type ListOfCountryNamesGroupedByContinent struct {
}

// ListOfCountryNamesGroupedByContinentResponse was auto-generated
// from WSDL.
type ListOfCountryNamesGroupedByContinentResponse struct {
	ListOfCountryNamesGroupedByContinentResult *ArrayOftCountryCodeAndNameGroupedByContinent `xml:"ListOfCountryNamesGroupedByContinentResult,omitempty" json:"ListOfCountryNamesGroupedByContinentResult,omitempty" yaml:"ListOfCountryNamesGroupedByContinentResult,omitempty"`
}

// ListOfCurrenciesByCode was auto-generated from WSDL.
type ListOfCurrenciesByCode struct {
}

// ListOfCurrenciesByCodeResponse was auto-generated from WSDL.
type ListOfCurrenciesByCodeResponse struct {
	ListOfCurrenciesByCodeResult *ArrayOftCurrency `xml:"ListOfCurrenciesByCodeResult,omitempty" json:"ListOfCurrenciesByCodeResult,omitempty" yaml:"ListOfCurrenciesByCodeResult,omitempty"`
}

// ListOfCurrenciesByName was auto-generated from WSDL.
type ListOfCurrenciesByName struct {
}

// ListOfCurrenciesByNameResponse was auto-generated from WSDL.
type ListOfCurrenciesByNameResponse struct {
	ListOfCurrenciesByNameResult *ArrayOftCurrency `xml:"ListOfCurrenciesByNameResult,omitempty" json:"ListOfCurrenciesByNameResult,omitempty" yaml:"ListOfCurrenciesByNameResult,omitempty"`
}

// ListOfLanguagesByCode was auto-generated from WSDL.
type ListOfLanguagesByCode struct {
}

// ListOfLanguagesByCodeResponse was auto-generated from WSDL.
type ListOfLanguagesByCodeResponse struct {
	ListOfLanguagesByCodeResult *ArrayOftLanguage `xml:"ListOfLanguagesByCodeResult,omitempty" json:"ListOfLanguagesByCodeResult,omitempty" yaml:"ListOfLanguagesByCodeResult,omitempty"`
}

// ListOfLanguagesByName was auto-generated from WSDL.
type ListOfLanguagesByName struct {
}

// ListOfLanguagesByNameResponse was auto-generated from WSDL.
type ListOfLanguagesByNameResponse struct {
	ListOfLanguagesByNameResult *ArrayOftLanguage `xml:"ListOfLanguagesByNameResult,omitempty" json:"ListOfLanguagesByNameResult,omitempty" yaml:"ListOfLanguagesByNameResult,omitempty"`
}

// TContinent was auto-generated from WSDL.
type TContinent struct {
	SCode *string `xml:"sCode,omitempty" json:"sCode,omitempty" yaml:"sCode,omitempty"`
	SName *string `xml:"sName,omitempty" json:"sName,omitempty" yaml:"sName,omitempty"`
}

// TCountryCodeAndName was auto-generated from WSDL.
type TCountryCodeAndName struct {
	SISOCode *string `xml:"sISOCode,omitempty" json:"sISOCode,omitempty" yaml:"sISOCode,omitempty"`
	SName    *string `xml:"sName,omitempty" json:"sName,omitempty" yaml:"sName,omitempty"`
}

// TCountryCodeAndNameGroupedByContinent was auto-generated from
// WSDL.
type TCountryCodeAndNameGroupedByContinent struct {
	Continent           *TContinent                 `xml:"Continent,omitempty" json:"Continent,omitempty" yaml:"Continent,omitempty"`
	CountryCodeAndNames *ArrayOftCountryCodeAndName `xml:"CountryCodeAndNames,omitempty" json:"CountryCodeAndNames,omitempty" yaml:"CountryCodeAndNames,omitempty"`
}

// TCountryInfo was auto-generated from WSDL.
type TCountryInfo struct {
	SISOCode         *string           `xml:"sISOCode,omitempty" json:"sISOCode,omitempty" yaml:"sISOCode,omitempty"`
	SName            *string           `xml:"sName,omitempty" json:"sName,omitempty" yaml:"sName,omitempty"`
	SCapitalCity     *string           `xml:"sCapitalCity,omitempty" json:"sCapitalCity,omitempty" yaml:"sCapitalCity,omitempty"`
	SPhoneCode       *string           `xml:"sPhoneCode,omitempty" json:"sPhoneCode,omitempty" yaml:"sPhoneCode,omitempty"`
	SContinentCode   *string           `xml:"sContinentCode,omitempty" json:"sContinentCode,omitempty" yaml:"sContinentCode,omitempty"`
	SCurrencyISOCode *string           `xml:"sCurrencyISOCode,omitempty" json:"sCurrencyISOCode,omitempty" yaml:"sCurrencyISOCode,omitempty"`
	SCountryFlag     *string           `xml:"sCountryFlag,omitempty" json:"sCountryFlag,omitempty" yaml:"sCountryFlag,omitempty"`
	Languages        *ArrayOftLanguage `xml:"Languages,omitempty" json:"Languages,omitempty" yaml:"Languages,omitempty"`
}

// TCurrency was auto-generated from WSDL.
type TCurrency struct {
	SISOCode *string `xml:"sISOCode,omitempty" json:"sISOCode,omitempty" yaml:"sISOCode,omitempty"`
	SName    *string `xml:"sName,omitempty" json:"sName,omitempty" yaml:"sName,omitempty"`
}

// TLanguage was auto-generated from WSDL.
type TLanguage struct {
	SISOCode *string `xml:"sISOCode,omitempty" json:"sISOCode,omitempty" yaml:"sISOCode,omitempty"`
	SName    *string `xml:"sName,omitempty" json:"sName,omitempty" yaml:"sName,omitempty"`
}

// Operation wrapper for CapitalCity.
// OperationCapitalCitySoapRequest was auto-generated from WSDL.
type OperationCapitalCitySoapRequest struct {
	CapitalCity *CapitalCity `xml:"CapitalCity,omitempty" json:"CapitalCity,omitempty" yaml:"CapitalCity,omitempty"`
}

// Operation wrapper for CapitalCity.
// OperationCapitalCitySoapResponse was auto-generated from WSDL.
type OperationCapitalCitySoapResponse struct {
	CapitalCityResponse *CapitalCityResponse `xml:"CapitalCityResponse,omitempty" json:"CapitalCityResponse,omitempty" yaml:"CapitalCityResponse,omitempty"`
}

// Operation wrapper for CountriesUsingCurrency.
// OperationCountriesUsingCurrencySoapRequest was auto-generated
// from WSDL.
type OperationCountriesUsingCurrencySoapRequest struct {
	CountriesUsingCurrency *CountriesUsingCurrency `xml:"CountriesUsingCurrency,omitempty" json:"CountriesUsingCurrency,omitempty" yaml:"CountriesUsingCurrency,omitempty"`
}

// Operation wrapper for CountriesUsingCurrency.
// OperationCountriesUsingCurrencySoapResponse was auto-generated
// from WSDL.
type OperationCountriesUsingCurrencySoapResponse struct {
	CountriesUsingCurrencyResponse *CountriesUsingCurrencyResponse `xml:"CountriesUsingCurrencyResponse,omitempty" json:"CountriesUsingCurrencyResponse,omitempty" yaml:"CountriesUsingCurrencyResponse,omitempty"`
}

// Operation wrapper for CountryCurrency.
// OperationCountryCurrencySoapRequest was auto-generated from
// WSDL.
type OperationCountryCurrencySoapRequest struct {
	CountryCurrency *CountryCurrency `xml:"CountryCurrency,omitempty" json:"CountryCurrency,omitempty" yaml:"CountryCurrency,omitempty"`
}

// Operation wrapper for CountryCurrency.
// OperationCountryCurrencySoapResponse was auto-generated from
// WSDL.
type OperationCountryCurrencySoapResponse struct {
	CountryCurrencyResponse *CountryCurrencyResponse `xml:"CountryCurrencyResponse,omitempty" json:"CountryCurrencyResponse,omitempty" yaml:"CountryCurrencyResponse,omitempty"`
}

// Operation wrapper for CountryFlag.
// OperationCountryFlagSoapRequest was auto-generated from WSDL.
type OperationCountryFlagSoapRequest struct {
	CountryFlag *CountryFlag `xml:"CountryFlag,omitempty" json:"CountryFlag,omitempty" yaml:"CountryFlag,omitempty"`
}

// Operation wrapper for CountryFlag.
// OperationCountryFlagSoapResponse was auto-generated from WSDL.
type OperationCountryFlagSoapResponse struct {
	CountryFlagResponse *CountryFlagResponse `xml:"CountryFlagResponse,omitempty" json:"CountryFlagResponse,omitempty" yaml:"CountryFlagResponse,omitempty"`
}

// Operation wrapper for CountryISOCode.
// OperationCountryISOCodeSoapRequest was auto-generated from WSDL.
type OperationCountryISOCodeSoapRequest struct {
	CountryISOCode *CountryISOCode `xml:"CountryISOCode,omitempty" json:"CountryISOCode,omitempty" yaml:"CountryISOCode,omitempty"`
}

// Operation wrapper for CountryISOCode.
// OperationCountryISOCodeSoapResponse was auto-generated from
// WSDL.
type OperationCountryISOCodeSoapResponse struct {
	CountryISOCodeResponse *CountryISOCodeResponse `xml:"CountryISOCodeResponse,omitempty" json:"CountryISOCodeResponse,omitempty" yaml:"CountryISOCodeResponse,omitempty"`
}

// Operation wrapper for CountryIntPhoneCode.
// OperationCountryIntPhoneCodeSoapRequest was auto-generated from
// WSDL.
type OperationCountryIntPhoneCodeSoapRequest struct {
	CountryIntPhoneCode *CountryIntPhoneCode `xml:"CountryIntPhoneCode,omitempty" json:"CountryIntPhoneCode,omitempty" yaml:"CountryIntPhoneCode,omitempty"`
}

// Operation wrapper for CountryIntPhoneCode.
// OperationCountryIntPhoneCodeSoapResponse was auto-generated
// from WSDL.
type OperationCountryIntPhoneCodeSoapResponse struct {
	CountryIntPhoneCodeResponse *CountryIntPhoneCodeResponse `xml:"CountryIntPhoneCodeResponse,omitempty" json:"CountryIntPhoneCodeResponse,omitempty" yaml:"CountryIntPhoneCodeResponse,omitempty"`
}

// Operation wrapper for CountryName.
// OperationCountryNameSoapRequest was auto-generated from WSDL.
type OperationCountryNameSoapRequest struct {
	CountryName *CountryName `xml:"CountryName,omitempty" json:"CountryName,omitempty" yaml:"CountryName,omitempty"`
}

// Operation wrapper for CountryName.
// OperationCountryNameSoapResponse was auto-generated from WSDL.
type OperationCountryNameSoapResponse struct {
	CountryNameResponse *CountryNameResponse `xml:"CountryNameResponse,omitempty" json:"CountryNameResponse,omitempty" yaml:"CountryNameResponse,omitempty"`
}

// Operation wrapper for CurrencyName.
// OperationCurrencyNameSoapRequest was auto-generated from WSDL.
type OperationCurrencyNameSoapRequest struct {
	CurrencyName *CurrencyName `xml:"CurrencyName,omitempty" json:"CurrencyName,omitempty" yaml:"CurrencyName,omitempty"`
}

// Operation wrapper for CurrencyName.
// OperationCurrencyNameSoapResponse was auto-generated from WSDL.
type OperationCurrencyNameSoapResponse struct {
	CurrencyNameResponse *CurrencyNameResponse `xml:"CurrencyNameResponse,omitempty" json:"CurrencyNameResponse,omitempty" yaml:"CurrencyNameResponse,omitempty"`
}

// Operation wrapper for FullCountryInfo.
// OperationFullCountryInfoSoapRequest was auto-generated from
// WSDL.
type OperationFullCountryInfoSoapRequest struct {
	FullCountryInfo *FullCountryInfo `xml:"FullCountryInfo,omitempty" json:"FullCountryInfo,omitempty" yaml:"FullCountryInfo,omitempty"`
}

// Operation wrapper for FullCountryInfo.
// OperationFullCountryInfoSoapResponse was auto-generated from
// WSDL.
type OperationFullCountryInfoSoapResponse struct {
	FullCountryInfoResponse *FullCountryInfoResponse `xml:"FullCountryInfoResponse,omitempty" json:"FullCountryInfoResponse,omitempty" yaml:"FullCountryInfoResponse,omitempty"`
}

// Operation wrapper for FullCountryInfoAllCountries.
// OperationFullCountryInfoAllCountriesSoapRequest was auto-generated
// from WSDL.
type OperationFullCountryInfoAllCountriesSoapRequest struct {
	FullCountryInfoAllCountries *FullCountryInfoAllCountries `xml:"FullCountryInfoAllCountries,omitempty" json:"FullCountryInfoAllCountries,omitempty" yaml:"FullCountryInfoAllCountries,omitempty"`
}

// Operation wrapper for FullCountryInfoAllCountries.
// OperationFullCountryInfoAllCountriesSoapResponse was auto-generated
// from WSDL.
type OperationFullCountryInfoAllCountriesSoapResponse struct {
	FullCountryInfoAllCountriesResponse *FullCountryInfoAllCountriesResponse `xml:"FullCountryInfoAllCountriesResponse,omitempty" json:"FullCountryInfoAllCountriesResponse,omitempty" yaml:"FullCountryInfoAllCountriesResponse,omitempty"`
}

// Operation wrapper for LanguageISOCode.
// OperationLanguageISOCodeSoapRequest was auto-generated from
// WSDL.
type OperationLanguageISOCodeSoapRequest struct {
	LanguageISOCode *LanguageISOCode `xml:"LanguageISOCode,omitempty" json:"LanguageISOCode,omitempty" yaml:"LanguageISOCode,omitempty"`
}

// Operation wrapper for LanguageISOCode.
// OperationLanguageISOCodeSoapResponse was auto-generated from
// WSDL.
type OperationLanguageISOCodeSoapResponse struct {
	LanguageISOCodeResponse *LanguageISOCodeResponse `xml:"LanguageISOCodeResponse,omitempty" json:"LanguageISOCodeResponse,omitempty" yaml:"LanguageISOCodeResponse,omitempty"`
}

// Operation wrapper for LanguageName.
// OperationLanguageNameSoapRequest was auto-generated from WSDL.
type OperationLanguageNameSoapRequest struct {
	LanguageName *LanguageName `xml:"LanguageName,omitempty" json:"LanguageName,omitempty" yaml:"LanguageName,omitempty"`
}

// Operation wrapper for LanguageName.
// OperationLanguageNameSoapResponse was auto-generated from WSDL.
type OperationLanguageNameSoapResponse struct {
	LanguageNameResponse *LanguageNameResponse `xml:"LanguageNameResponse,omitempty" json:"LanguageNameResponse,omitempty" yaml:"LanguageNameResponse,omitempty"`
}

// Operation wrapper for ListOfContinentsByCode.
// OperationListOfContinentsByCodeSoapRequest was auto-generated
// from WSDL.
type OperationListOfContinentsByCodeSoapRequest struct {
	ListOfContinentsByCode *ListOfContinentsByCode `xml:"ListOfContinentsByCode,omitempty" json:"ListOfContinentsByCode,omitempty" yaml:"ListOfContinentsByCode,omitempty"`
}

// Operation wrapper for ListOfContinentsByCode.
// OperationListOfContinentsByCodeSoapResponse was auto-generated
// from WSDL.
type OperationListOfContinentsByCodeSoapResponse struct {
	ListOfContinentsByCodeResponse *ListOfContinentsByCodeResponse `xml:"ListOfContinentsByCodeResponse,omitempty" json:"ListOfContinentsByCodeResponse,omitempty" yaml:"ListOfContinentsByCodeResponse,omitempty"`
}

// Operation wrapper for ListOfContinentsByName.
// OperationListOfContinentsByNameSoapRequest was auto-generated
// from WSDL.
type OperationListOfContinentsByNameSoapRequest struct {
	ListOfContinentsByName *ListOfContinentsByName `xml:"ListOfContinentsByName,omitempty" json:"ListOfContinentsByName,omitempty" yaml:"ListOfContinentsByName,omitempty"`
}

// Operation wrapper for ListOfContinentsByName.
// OperationListOfContinentsByNameSoapResponse was auto-generated
// from WSDL.
type OperationListOfContinentsByNameSoapResponse struct {
	ListOfContinentsByNameResponse *ListOfContinentsByNameResponse `xml:"ListOfContinentsByNameResponse,omitempty" json:"ListOfContinentsByNameResponse,omitempty" yaml:"ListOfContinentsByNameResponse,omitempty"`
}

// Operation wrapper for ListOfCountryNamesByCode.
// OperationListOfCountryNamesByCodeSoapRequest was auto-generated
// from WSDL.
type OperationListOfCountryNamesByCodeSoapRequest struct {
	ListOfCountryNamesByCode *ListOfCountryNamesByCode `xml:"ListOfCountryNamesByCode,omitempty" json:"ListOfCountryNamesByCode,omitempty" yaml:"ListOfCountryNamesByCode,omitempty"`
}

// Operation wrapper for ListOfCountryNamesByCode.
// OperationListOfCountryNamesByCodeSoapResponse was auto-generated
// from WSDL.
type OperationListOfCountryNamesByCodeSoapResponse struct {
	ListOfCountryNamesByCodeResponse *ListOfCountryNamesByCodeResponse `xml:"ListOfCountryNamesByCodeResponse,omitempty" json:"ListOfCountryNamesByCodeResponse,omitempty" yaml:"ListOfCountryNamesByCodeResponse,omitempty"`
}

// Operation wrapper for ListOfCountryNamesByName.
// OperationListOfCountryNamesByNameSoapRequest was auto-generated
// from WSDL.
type OperationListOfCountryNamesByNameSoapRequest struct {
	ListOfCountryNamesByName *ListOfCountryNamesByName `xml:"ListOfCountryNamesByName,omitempty" json:"ListOfCountryNamesByName,omitempty" yaml:"ListOfCountryNamesByName,omitempty"`
}

// Operation wrapper for ListOfCountryNamesByName.
// OperationListOfCountryNamesByNameSoapResponse was auto-generated
// from WSDL.
type OperationListOfCountryNamesByNameSoapResponse struct {
	ListOfCountryNamesByNameResponse *ListOfCountryNamesByNameResponse `xml:"ListOfCountryNamesByNameResponse,omitempty" json:"ListOfCountryNamesByNameResponse,omitempty" yaml:"ListOfCountryNamesByNameResponse,omitempty"`
}

// Operation wrapper for ListOfCountryNamesGroupedByContinent.
// OperationListOfCountryNamesGroupedByContinentSoapRequest was
// auto-generated from WSDL.
type OperationListOfCountryNamesGroupedByContinentSoapRequest struct {
	ListOfCountryNamesGroupedByContinent *ListOfCountryNamesGroupedByContinent `xml:"ListOfCountryNamesGroupedByContinent,omitempty" json:"ListOfCountryNamesGroupedByContinent,omitempty" yaml:"ListOfCountryNamesGroupedByContinent,omitempty"`
}

// Operation wrapper for ListOfCountryNamesGroupedByContinent.
// OperationListOfCountryNamesGroupedByContinentSoapResponse was
// auto-generated from WSDL.
type OperationListOfCountryNamesGroupedByContinentSoapResponse struct {
	ListOfCountryNamesGroupedByContinentResponse *ListOfCountryNamesGroupedByContinentResponse `xml:"ListOfCountryNamesGroupedByContinentResponse,omitempty" json:"ListOfCountryNamesGroupedByContinentResponse,omitempty" yaml:"ListOfCountryNamesGroupedByContinentResponse,omitempty"`
}

// Operation wrapper for ListOfCurrenciesByCode.
// OperationListOfCurrenciesByCodeSoapRequest was auto-generated
// from WSDL.
type OperationListOfCurrenciesByCodeSoapRequest struct {
	ListOfCurrenciesByCode *ListOfCurrenciesByCode `xml:"ListOfCurrenciesByCode,omitempty" json:"ListOfCurrenciesByCode,omitempty" yaml:"ListOfCurrenciesByCode,omitempty"`
}

// Operation wrapper for ListOfCurrenciesByCode.
// OperationListOfCurrenciesByCodeSoapResponse was auto-generated
// from WSDL.
type OperationListOfCurrenciesByCodeSoapResponse struct {
	ListOfCurrenciesByCodeResponse *ListOfCurrenciesByCodeResponse `xml:"ListOfCurrenciesByCodeResponse,omitempty" json:"ListOfCurrenciesByCodeResponse,omitempty" yaml:"ListOfCurrenciesByCodeResponse,omitempty"`
}

// Operation wrapper for ListOfCurrenciesByName.
// OperationListOfCurrenciesByNameSoapRequest was auto-generated
// from WSDL.
type OperationListOfCurrenciesByNameSoapRequest struct {
	ListOfCurrenciesByName *ListOfCurrenciesByName `xml:"ListOfCurrenciesByName,omitempty" json:"ListOfCurrenciesByName,omitempty" yaml:"ListOfCurrenciesByName,omitempty"`
}

// Operation wrapper for ListOfCurrenciesByName.
// OperationListOfCurrenciesByNameSoapResponse was auto-generated
// from WSDL.
type OperationListOfCurrenciesByNameSoapResponse struct {
	ListOfCurrenciesByNameResponse *ListOfCurrenciesByNameResponse `xml:"ListOfCurrenciesByNameResponse,omitempty" json:"ListOfCurrenciesByNameResponse,omitempty" yaml:"ListOfCurrenciesByNameResponse,omitempty"`
}

// Operation wrapper for ListOfLanguagesByCode.
// OperationListOfLanguagesByCodeSoapRequest was auto-generated
// from WSDL.
type OperationListOfLanguagesByCodeSoapRequest struct {
	ListOfLanguagesByCode *ListOfLanguagesByCode `xml:"ListOfLanguagesByCode,omitempty" json:"ListOfLanguagesByCode,omitempty" yaml:"ListOfLanguagesByCode,omitempty"`
}

// Operation wrapper for ListOfLanguagesByCode.
// OperationListOfLanguagesByCodeSoapResponse was auto-generated
// from WSDL.
type OperationListOfLanguagesByCodeSoapResponse struct {
	ListOfLanguagesByCodeResponse *ListOfLanguagesByCodeResponse `xml:"ListOfLanguagesByCodeResponse,omitempty" json:"ListOfLanguagesByCodeResponse,omitempty" yaml:"ListOfLanguagesByCodeResponse,omitempty"`
}

// Operation wrapper for ListOfLanguagesByName.
// OperationListOfLanguagesByNameSoapRequest was auto-generated
// from WSDL.
type OperationListOfLanguagesByNameSoapRequest struct {
	ListOfLanguagesByName *ListOfLanguagesByName `xml:"ListOfLanguagesByName,omitempty" json:"ListOfLanguagesByName,omitempty" yaml:"ListOfLanguagesByName,omitempty"`
}

// Operation wrapper for ListOfLanguagesByName.
// OperationListOfLanguagesByNameSoapResponse was auto-generated
// from WSDL.
type OperationListOfLanguagesByNameSoapResponse struct {
	ListOfLanguagesByNameResponse *ListOfLanguagesByNameResponse `xml:"ListOfLanguagesByNameResponse,omitempty" json:"ListOfLanguagesByNameResponse,omitempty" yaml:"ListOfLanguagesByNameResponse,omitempty"`
}

// countryInfoServiceSoapType implements the CountryInfoServiceSoapType interface.
type countryInfoServiceSoapType struct {
	cli *soap.Client
}

// Returns the  name of the captial city for the passed country
// code
func (p *countryInfoServiceSoapType) CapitalCity(CapitalCity *CapitalCity) (*CapitalCityResponse, error) {
	α := struct {
		OperationCapitalCitySoapRequest `xml:"tns:CapitalCity"`
	}{
		OperationCapitalCitySoapRequest{
			CapitalCity,
		},
	}

	γ := struct {
		OperationCapitalCitySoapResponse `xml:"CapitalCityResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("CapitalCity", α, &γ); err != nil {
		return nil, err
	}
	return γ.CapitalCityResponse, nil
}

// Returns a list of all countries that use the same currency code.
// Pass a ISO currency code
func (p *countryInfoServiceSoapType) CountriesUsingCurrency(CountriesUsingCurrency *CountriesUsingCurrency) (*CountriesUsingCurrencyResponse, error) {
	α := struct {
		OperationCountriesUsingCurrencySoapRequest `xml:"tns:CountriesUsingCurrency"`
	}{
		OperationCountriesUsingCurrencySoapRequest{
			CountriesUsingCurrency,
		},
	}

	γ := struct {
		OperationCountriesUsingCurrencySoapResponse `xml:"CountriesUsingCurrencyResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("CountriesUsingCurrency", α, &γ); err != nil {
		return nil, err
	}
	return γ.CountriesUsingCurrencyResponse, nil
}

// Returns the currency ISO code and name for the passed country
// ISO code
func (p *countryInfoServiceSoapType) CountryCurrency(CountryCurrency *CountryCurrency) (*CountryCurrencyResponse, error) {
	α := struct {
		OperationCountryCurrencySoapRequest `xml:"tns:CountryCurrency"`
	}{
		OperationCountryCurrencySoapRequest{
			CountryCurrency,
		},
	}

	γ := struct {
		OperationCountryCurrencySoapResponse `xml:"CountryCurrencyResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("CountryCurrency", α, &γ); err != nil {
		return nil, err
	}
	return γ.CountryCurrencyResponse, nil
}

// Returns a link to a picture of the country flag
func (p *countryInfoServiceSoapType) CountryFlag(CountryFlag *CountryFlag) (*CountryFlagResponse, error) {
	α := struct {
		OperationCountryFlagSoapRequest `xml:"tns:CountryFlag"`
	}{
		OperationCountryFlagSoapRequest{
			CountryFlag,
		},
	}

	γ := struct {
		OperationCountryFlagSoapResponse `xml:"CountryFlagResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("CountryFlag", α, &γ); err != nil {
		return nil, err
	}
	return γ.CountryFlagResponse, nil
}

// This function tries to found a country based on the passed country
// name.
func (p *countryInfoServiceSoapType) CountryISOCode(CountryISOCode *CountryISOCode) (*CountryISOCodeResponse, error) {
	α := struct {
		OperationCountryISOCodeSoapRequest `xml:"tns:CountryISOCode"`
	}{
		OperationCountryISOCodeSoapRequest{
			CountryISOCode,
		},
	}

	γ := struct {
		OperationCountryISOCodeSoapResponse `xml:"CountryISOCodeResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("CountryISOCode", α, &γ); err != nil {
		return nil, err
	}
	return γ.CountryISOCodeResponse, nil
}

// Returns the internation phone code for the passed ISO country
// code
func (p *countryInfoServiceSoapType) CountryIntPhoneCode(CountryIntPhoneCode *CountryIntPhoneCode) (*CountryIntPhoneCodeResponse, error) {
	α := struct {
		OperationCountryIntPhoneCodeSoapRequest `xml:"tns:CountryIntPhoneCode"`
	}{
		OperationCountryIntPhoneCodeSoapRequest{
			CountryIntPhoneCode,
		},
	}

	γ := struct {
		OperationCountryIntPhoneCodeSoapResponse `xml:"CountryIntPhoneCodeResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("CountryIntPhoneCode", α, &γ); err != nil {
		return nil, err
	}
	return γ.CountryIntPhoneCodeResponse, nil
}

// Searches the database for a country by the passed ISO country
// code
func (p *countryInfoServiceSoapType) CountryName(CountryName *CountryName) (*CountryNameResponse, error) {
	α := struct {
		OperationCountryNameSoapRequest `xml:"tns:CountryName"`
	}{
		OperationCountryNameSoapRequest{
			CountryName,
		},
	}

	γ := struct {
		OperationCountryNameSoapResponse `xml:"CountryNameResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("CountryName", α, &γ); err != nil {
		return nil, err
	}
	return γ.CountryNameResponse, nil
}

// Returns the name of the currency (if found)
func (p *countryInfoServiceSoapType) CurrencyName(CurrencyName *CurrencyName) (*CurrencyNameResponse, error) {
	α := struct {
		OperationCurrencyNameSoapRequest `xml:"tns:CurrencyName"`
	}{
		OperationCurrencyNameSoapRequest{
			CurrencyName,
		},
	}

	γ := struct {
		OperationCurrencyNameSoapResponse `xml:"CurrencyNameResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("CurrencyName", α, &γ); err != nil {
		return nil, err
	}
	return γ.CurrencyNameResponse, nil
}

// Returns a struct with all the stored country information. Pass
// the ISO country code
func (p *countryInfoServiceSoapType) FullCountryInfo(FullCountryInfo *FullCountryInfo) (*FullCountryInfoResponse, error) {
	α := struct {
		OperationFullCountryInfoSoapRequest `xml:"tns:FullCountryInfo"`
	}{
		OperationFullCountryInfoSoapRequest{
			FullCountryInfo,
		},
	}

	γ := struct {
		OperationFullCountryInfoSoapResponse `xml:"FullCountryInfoResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("FullCountryInfo", α, &γ); err != nil {
		return nil, err
	}
	return γ.FullCountryInfoResponse, nil
}

// Returns an array with all countries and all the language information
// stored
func (p *countryInfoServiceSoapType) FullCountryInfoAllCountries(FullCountryInfoAllCountries *FullCountryInfoAllCountries) (*FullCountryInfoAllCountriesResponse, error) {
	α := struct {
		OperationFullCountryInfoAllCountriesSoapRequest `xml:"tns:FullCountryInfoAllCountries"`
	}{
		OperationFullCountryInfoAllCountriesSoapRequest{
			FullCountryInfoAllCountries,
		},
	}

	γ := struct {
		OperationFullCountryInfoAllCountriesSoapResponse `xml:"FullCountryInfoAllCountriesResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("FullCountryInfoAllCountries", α, &γ); err != nil {
		return nil, err
	}
	return γ.FullCountryInfoAllCountriesResponse, nil
}

// Find a language ISO code based on the passed language name
func (p *countryInfoServiceSoapType) LanguageISOCode(LanguageISOCode *LanguageISOCode) (*LanguageISOCodeResponse, error) {
	α := struct {
		OperationLanguageISOCodeSoapRequest `xml:"tns:LanguageISOCode"`
	}{
		OperationLanguageISOCodeSoapRequest{
			LanguageISOCode,
		},
	}

	γ := struct {
		OperationLanguageISOCodeSoapResponse `xml:"LanguageISOCodeResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("LanguageISOCode", α, &γ); err != nil {
		return nil, err
	}
	return γ.LanguageISOCodeResponse, nil
}

// Find a language name based on the passed ISO language code
func (p *countryInfoServiceSoapType) LanguageName(LanguageName *LanguageName) (*LanguageNameResponse, error) {
	α := struct {
		OperationLanguageNameSoapRequest `xml:"tns:LanguageName"`
	}{
		OperationLanguageNameSoapRequest{
			LanguageName,
		},
	}

	γ := struct {
		OperationLanguageNameSoapResponse `xml:"LanguageNameResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("LanguageName", α, &γ); err != nil {
		return nil, err
	}
	return γ.LanguageNameResponse, nil
}

// Returns a list of continents ordered by code.
func (p *countryInfoServiceSoapType) ListOfContinentsByCode(ListOfContinentsByCode *ListOfContinentsByCode) (*ListOfContinentsByCodeResponse, error) {
	α := struct {
		OperationListOfContinentsByCodeSoapRequest `xml:"tns:ListOfContinentsByCode"`
	}{
		OperationListOfContinentsByCodeSoapRequest{
			ListOfContinentsByCode,
		},
	}

	γ := struct {
		OperationListOfContinentsByCodeSoapResponse `xml:"ListOfContinentsByCodeResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("ListOfContinentsByCode", α, &γ); err != nil {
		return nil, err
	}
	return γ.ListOfContinentsByCodeResponse, nil
}

// Returns a list of continents ordered by name.
func (p *countryInfoServiceSoapType) ListOfContinentsByName(ListOfContinentsByName *ListOfContinentsByName) (*ListOfContinentsByNameResponse, error) {
	α := struct {
		OperationListOfContinentsByNameSoapRequest `xml:"tns:ListOfContinentsByName"`
	}{
		OperationListOfContinentsByNameSoapRequest{
			ListOfContinentsByName,
		},
	}

	γ := struct {
		OperationListOfContinentsByNameSoapResponse `xml:"ListOfContinentsByNameResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("ListOfContinentsByName", α, &γ); err != nil {
		return nil, err
	}
	return γ.ListOfContinentsByNameResponse, nil
}

// Returns a list of all stored counties ordered by ISO code
func (p *countryInfoServiceSoapType) ListOfCountryNamesByCode(ListOfCountryNamesByCode *ListOfCountryNamesByCode) (*ListOfCountryNamesByCodeResponse, error) {
	α := struct {
		OperationListOfCountryNamesByCodeSoapRequest `xml:"tns:ListOfCountryNamesByCode"`
	}{
		OperationListOfCountryNamesByCodeSoapRequest{
			ListOfCountryNamesByCode,
		},
	}

	γ := struct {
		OperationListOfCountryNamesByCodeSoapResponse `xml:"ListOfCountryNamesByCodeResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("ListOfCountryNamesByCode", α, &γ); err != nil {
		return nil, err
	}
	return γ.ListOfCountryNamesByCodeResponse, nil
}

// Returns a list of all stored counties ordered by country name
func (p *countryInfoServiceSoapType) ListOfCountryNamesByName(ListOfCountryNamesByName *ListOfCountryNamesByName) (*ListOfCountryNamesByNameResponse, error) {
	α := struct {
		OperationListOfCountryNamesByNameSoapRequest `xml:"tns:ListOfCountryNamesByName"`
	}{
		OperationListOfCountryNamesByNameSoapRequest{
			ListOfCountryNamesByName,
		},
	}

	γ := struct {
		OperationListOfCountryNamesByNameSoapResponse `xml:"ListOfCountryNamesByNameResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("ListOfCountryNamesByName", α, &γ); err != nil {
		return nil, err
	}
	return γ.ListOfCountryNamesByNameResponse, nil
}

// Returns a list of all stored counties grouped per continent
func (p *countryInfoServiceSoapType) ListOfCountryNamesGroupedByContinent(ListOfCountryNamesGroupedByContinent *ListOfCountryNamesGroupedByContinent) (*ListOfCountryNamesGroupedByContinentResponse, error) {
	α := struct {
		OperationListOfCountryNamesGroupedByContinentSoapRequest `xml:"tns:ListOfCountryNamesGroupedByContinent"`
	}{
		OperationListOfCountryNamesGroupedByContinentSoapRequest{
			ListOfCountryNamesGroupedByContinent,
		},
	}

	γ := struct {
		OperationListOfCountryNamesGroupedByContinentSoapResponse `xml:"ListOfCountryNamesGroupedByContinentResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("ListOfCountryNamesGroupedByContinent", α, &γ); err != nil {
		return nil, err
	}
	return γ.ListOfCountryNamesGroupedByContinentResponse, nil
}

// Returns a list of currencies ordered by code.
func (p *countryInfoServiceSoapType) ListOfCurrenciesByCode(ListOfCurrenciesByCode *ListOfCurrenciesByCode) (*ListOfCurrenciesByCodeResponse, error) {
	α := struct {
		OperationListOfCurrenciesByCodeSoapRequest `xml:"tns:ListOfCurrenciesByCode"`
	}{
		OperationListOfCurrenciesByCodeSoapRequest{
			ListOfCurrenciesByCode,
		},
	}

	γ := struct {
		OperationListOfCurrenciesByCodeSoapResponse `xml:"ListOfCurrenciesByCodeResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("ListOfCurrenciesByCode", α, &γ); err != nil {
		return nil, err
	}
	return γ.ListOfCurrenciesByCodeResponse, nil
}

// Returns a list of currencies ordered by name.
func (p *countryInfoServiceSoapType) ListOfCurrenciesByName(ListOfCurrenciesByName *ListOfCurrenciesByName) (*ListOfCurrenciesByNameResponse, error) {
	α := struct {
		OperationListOfCurrenciesByNameSoapRequest `xml:"tns:ListOfCurrenciesByName"`
	}{
		OperationListOfCurrenciesByNameSoapRequest{
			ListOfCurrenciesByName,
		},
	}

	γ := struct {
		OperationListOfCurrenciesByNameSoapResponse `xml:"ListOfCurrenciesByNameResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("ListOfCurrenciesByName", α, &γ); err != nil {
		return nil, err
	}
	return γ.ListOfCurrenciesByNameResponse, nil
}

// Returns an array of languages ordered by code
func (p *countryInfoServiceSoapType) ListOfLanguagesByCode(ListOfLanguagesByCode *ListOfLanguagesByCode) (*ListOfLanguagesByCodeResponse, error) {
	α := struct {
		OperationListOfLanguagesByCodeSoapRequest `xml:"tns:ListOfLanguagesByCode"`
	}{
		OperationListOfLanguagesByCodeSoapRequest{
			ListOfLanguagesByCode,
		},
	}

	γ := struct {
		OperationListOfLanguagesByCodeSoapResponse `xml:"ListOfLanguagesByCodeResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("ListOfLanguagesByCode", α, &γ); err != nil {
		return nil, err
	}
	return γ.ListOfLanguagesByCodeResponse, nil
}

// Returns an array of languages ordered by name
func (p *countryInfoServiceSoapType) ListOfLanguagesByName(ListOfLanguagesByName *ListOfLanguagesByName) (*ListOfLanguagesByNameResponse, error) {
	α := struct {
		OperationListOfLanguagesByNameSoapRequest `xml:"tns:ListOfLanguagesByName"`
	}{
		OperationListOfLanguagesByNameSoapRequest{
			ListOfLanguagesByName,
		},
	}

	γ := struct {
		OperationListOfLanguagesByNameSoapResponse `xml:"ListOfLanguagesByNameResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("ListOfLanguagesByName", α, &γ); err != nil {
		return nil, err
	}
	return γ.ListOfLanguagesByNameResponse, nil
}
